local r = require
r('Plugs.plugins')
r('Plugs.autopairs')
r('Plugs.cmp')
r('Plugs.lsp')
r('Plugs.onenord')
r('Plugs.bufferlines')
r('Plugs.comment')
r('Plugs.blankline')
r('Plugs.lualine')
r('Plugs.mason')
r('Plugs.nvim-tree')
r('Plugs.treesitter')
r('Plugs.key')
