-- local M = {}
--
-- M.config = {
-- 	"folke/noice.nvim",
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("noice").setup({
-- 			lsp = {
-- 				override = {
-- 					["vim.lsp.util.convert_input_to_markdown_lines"] = true,
-- 					["vim.lsp.util.stylize_markdown"] = true,
-- 					["cmp.entry.get_documentation"] = true,
-- 				},
-- 			},
-- 			presets = {
-- 				bottom_search = true,
-- 				command_palette = true,
-- 				long_message_to_split = true,
-- 				inc_rename = false,
-- 				lsp_doc_border = true,
-- 			},
--       messages = {
--         enabled = false
--       }
-- 		})
-- 	end,
-- 	dependencies = {
-- 		"rcarriga/nvim-notify",
-- 		config = function()
-- 			require("notify").setup({
-- 				timeout = 1500,
-- 				fps = 60,
-- 				minimum_width = 20,
-- 			})
-- 		end,
-- 	},
-- }
--
-- return M
